run:
  timeout: 5m
  skip-dirs:
    - "docs/"
    - "scheduler-ui"

linters:
  enable-all: true
  disable:
    - gci
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    - interfacer
    - ifshort
    - golint
    - exhaustivestruct
    - deadcode
    - depguard
