// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: history.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createHistory = `-- name: CreateHistory :one
INSERT INTO history (
  schedule,
  status,
  details,
  scehduled_at,
  started_at,
  completed_at
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING schedule, status, details, scehduled_at, started_at, completed_at
`

type CreateHistoryParams struct {
	Schedule    uuid.UUID `json:"schedule"`
	Status      Status    `json:"status"`
	Details     string    `json:"details"`
	ScehduledAt time.Time `json:"scehduled_at"`
	StartedAt   time.Time `json:"started_at"`
	CompletedAt time.Time `json:"completed_at"`
}

func (q *Queries) CreateHistory(ctx context.Context, arg CreateHistoryParams) (History, error) {
	row := q.db.QueryRowContext(ctx, createHistory,
		arg.Schedule,
		arg.Status,
		arg.Details,
		arg.ScehduledAt,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i History
	err := row.Scan(
		&i.Schedule,
		&i.Status,
		&i.Details,
		&i.ScehduledAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listHistory = `-- name: ListHistory :many
SELECT schedule, status, details, scehduled_at, started_at, completed_at FROM history
WHERE schedule = $1
ORDER BY scehduled_at
LIMIT $2
OFFSET $3
`

type ListHistoryParams struct {
	Schedule uuid.UUID `json:"schedule"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListHistory(ctx context.Context, arg ListHistoryParams) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, listHistory, arg.Schedule, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []History{}
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.Schedule,
			&i.Status,
			&i.Details,
			&i.ScehduledAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
