// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: next_occurence.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const assignUnassignedWork = `-- name: AssignUnassignedWork :exec
UPDATE next_occurence 
SET worker = $1
WHERE occurence < (CURRENT_TIMESTAMP + $2 * INTERVAL '1 second') and worker IS NULL
`

type AssignUnassignedWorkParams struct {
	Worker  uuid.NullUUID `json:"worker"`
	Column2 interface{}   `json:"column_2"`
}

func (q *Queries) AssignUnassignedWork(ctx context.Context, arg AssignUnassignedWorkParams) error {
	_, err := q.db.ExecContext(ctx, assignUnassignedWork, arg.Worker, arg.Column2)
	return err
}

const createOccurence = `-- name: CreateOccurence :one
INSERT INTO next_occurence (
  schedule,
  worker,
  manual,
  status,
  occurence,
  last_updated
) VALUES (
  $1, $2, $3, $4, $5, now()
) RETURNING id, schedule, worker, manual, status, occurence, last_updated
`

type CreateOccurenceParams struct {
	Schedule  uuid.UUID     `json:"schedule"`
	Worker    uuid.NullUUID `json:"worker"`
	Manual    bool          `json:"manual"`
	Status    Status        `json:"status"`
	Occurence sql.NullTime  `json:"occurence"`
}

func (q *Queries) CreateOccurence(ctx context.Context, arg CreateOccurenceParams) (NextOccurence, error) {
	row := q.db.QueryRowContext(ctx, createOccurence,
		arg.Schedule,
		arg.Worker,
		arg.Manual,
		arg.Status,
		arg.Occurence,
	)
	var i NextOccurence
	err := row.Scan(
		&i.ID,
		&i.Schedule,
		&i.Worker,
		&i.Manual,
		&i.Status,
		&i.Occurence,
		&i.LastUpdated,
	)
	return i, err
}

const deleteOccurence = `-- name: DeleteOccurence :exec
DELETE FROM next_occurence
WHERE id = $1
`

func (q *Queries) DeleteOccurence(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteOccurence, id)
	return err
}

const getNextImmediateWork = `-- name: GetNextImmediateWork :one
SELECT MIN(occurence)::timestamptz FROM next_occurence
WHERE occurence > CURRENT_TIMESTAMP and worker = $1
`

func (q *Queries) GetNextImmediateWork(ctx context.Context, worker uuid.NullUUID) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getNextImmediateWork, worker)
	var column_1 time.Time
	err := row.Scan(&column_1)
	return column_1, err
}

const getOccurence = `-- name: GetOccurence :one
SELECT id, schedule, worker, manual, status, occurence, last_updated FROM next_occurence
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOccurence(ctx context.Context, id int32) (NextOccurence, error) {
	row := q.db.QueryRowContext(ctx, getOccurence, id)
	var i NextOccurence
	err := row.Scan(
		&i.ID,
		&i.Schedule,
		&i.Worker,
		&i.Manual,
		&i.Status,
		&i.Occurence,
		&i.LastUpdated,
	)
	return i, err
}

const myExpiredWork = `-- name: MyExpiredWork :many
SELECT id, schedule, worker, manual, status, occurence, last_updated FROM next_occurence
WHERE occurence < CURRENT_TIMESTAMP and worker = $1
ORDER BY occurence
`

func (q *Queries) MyExpiredWork(ctx context.Context, worker uuid.NullUUID) ([]NextOccurence, error) {
	rows, err := q.db.QueryContext(ctx, myExpiredWork, worker)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NextOccurence{}
	for rows.Next() {
		var i NextOccurence
		if err := rows.Scan(
			&i.ID,
			&i.Schedule,
			&i.Worker,
			&i.Manual,
			&i.Status,
			&i.Occurence,
			&i.LastUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
