// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: schedules.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules (
  id,
  cron,
  hook,
  owner,
  active,
  till,
  last_modified
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING id, cron, hook, owner, active, till, created_at, last_modified
`

type CreateScheduleParams struct {
	ID           uuid.UUID `json:"id"`
	Cron         string    `json:"cron"`
	Hook         string    `json:"hook"`
	Owner        string    `json:"owner"`
	Active       bool      `json:"active"`
	Till         time.Time `json:"till"`
	LastModified time.Time `json:"last_modified"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, createSchedule,
		arg.ID,
		arg.Cron,
		arg.Hook,
		arg.Owner,
		arg.Active,
		arg.Till,
		arg.LastModified,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Cron,
		&i.Hook,
		&i.Owner,
		&i.Active,
		&i.Till,
		&i.CreatedAt,
		&i.LastModified,
	)
	return i, err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM schedules
WHERE id = $1
`

func (q *Queries) DeleteSchedule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSchedule, id)
	return err
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, cron, hook, owner, active, till, created_at, last_modified FROM schedules
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSchedule(ctx context.Context, id uuid.UUID) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, getSchedule, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Cron,
		&i.Hook,
		&i.Owner,
		&i.Active,
		&i.Till,
		&i.CreatedAt,
		&i.LastModified,
	)
	return i, err
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, cron, hook, owner, active, till, created_at, last_modified FROM schedules
WHERE owner = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListSchedulesParams struct {
	Owner  string `json:"owner"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListSchedules(ctx context.Context, arg ListSchedulesParams) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, listSchedules, arg.Owner, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.Cron,
			&i.Hook,
			&i.Owner,
			&i.Active,
			&i.Till,
			&i.CreatedAt,
			&i.LastModified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
